from shiny import ui
from shinywidgets import output_widget

preprocessed_shiny = ui.layout_sidebar(
    ui.sidebar(
        ui.h5("Variable Inspection"),
        ui.input_select("preprocessed_current_measurement", "Select metabolic variable", []),
        ui.input_select("preprocessed_grouped", "Select grouping", []),
        ui.input_action_button("edit_grouping", "Add/edit Metadata", width="100%"),
        ui.input_action_button("edit_metabolic_variable", "Add/Edit Metabolic Variable", width="100%"),
        ui.hr(style="margin: 4px 0;"),
        ui.h5("Data Trimming"),
        ui.div("Measurement start (day/hour/minute):"),
        ui.row(
            ui.input_date("preprocessed_measurement_start_date", None, width="140px"),
            ui.input_numeric(
                "preprocessed_measurement_start_time_hour",
                None,
                0,
                min=0,
                max=24,
                step=1,
                width="90px",
            ),
            ":",
            ui.input_numeric(
                "preprocessed_measurement_start_time_minute",
                None,
                00,
                min=0,
                max=60,
                step=1,
                width="90px",
            ),
        ),
        ui.div("Measurement end (day/hour/minute):"),
        ui.row(
            ui.input_date("preprocessed_measurement_end_date", None, width="140px"),
            ui.input_numeric(
                "preprocessed_measurement_end_time_hour",
                None,
                0,
                min=0,
                max=24,
                step=1,
                width="90px",
            ),
            ":",
            ui.input_numeric(
                "preprocessed_measurement_end_time_minute",
                None,
                00,
                min=0,
                max=60,
                step=1,
                width="90px",
            ),
        ),
        ui.div("Dark-phase start"),
        ui.row(
            ui.input_numeric(
                "preprocessed_night_start_hour",
                None,
                18,
                min=0,
                max=24,
                step=1,
                width="100px",
            ),
            ui.input_numeric(
                "preprocessed_night_start_minute",
                None,
                00,
                min=0,
                max=60,
                step=1,
                width="100px",
            ),
        ),
        ui.div("Dark-phase end"),
        ui.row(
            ui.input_numeric(
                "preprocessed_day_start_hour",
                None,
                6,
                min=0,
                max=24,
                step=1,
                width="100px",
            ),
            ui.input_numeric(
                "preprocessed_day_start_minute",
                None,
                00,
                min=0,
                max=60,
                step=1,
                width="100px",
            ),
        ),
        ui.input_checkbox(
            "preprocessed_all_same_day_start",
            "Make all samples start at the same day",
            False,
        ),
        ui.hr(style="margin: 4px 0;"),
        ui.h5("Options"),
        ui.input_selectize(
            "preprocessed_excluded_samples",
            "Exclude samples",
            choices=[],
            multiple=True,
        ),
        ui.input_radio_buttons(
            "preprocessed_plot_xlabel_day",
            "Plot x-labels for days:",
            choices={"date": "Show original date", "day": "Show 'Day 1', 'Day 2', ..."},
        ),
        width=350,
        height=750,
        open="always",
        position="left",
    ),
    ui.row(
        output_widget("preprocessed_plot"),
    ),
    ui.row(
        ui.column(8),
        ui.column(
            2,
            ui.download_button("preprocessed_data_downloader", "Download data", width="75%"),
            align="right",
        ),
        ui.column(
            2,
            ui.download_button("preprocessed_plot_downloader", "Download PDF", width="75%"),
            align="left",
        ),
    ),
)
